rladies/rladies.github.io

content/about-us/global-team/index.es.md

Translated About Us to Spanish.

index.es.md

---

content/about-us/global-team/index.es.md

Correct index.es.md

---

themes/hugo-rladies/layouts/partials/head/head.html

Restores original fullcalendar styling

#114 Fix broken calendar style

---

content/news/2023-04-11-global-team-recruiting/index.en.md

sorry @drmowinckels looks like i missed one

fix date fields in recruiting article

---

data/global_team/alumni/christin_zasada.json

This PR adds an end date for Cristin's entry (as discussed here: https://github.com/rladies/rladies.github.io/issues/186)

Add end date

---

content/directory/index.en.md

Because we now have a better  workflow ✨

update directory instructions

---

data/chapters/Botswana-south_east_district-Gaborone.json

@Athanasiamo
Hi Mo,
Please see the updated social media changes made to the R-Ladies Gaborone chapter including the Mastodon account and the new website.
Thanks for all the hard work 💜. 
Best,
Simisani

Create New Botswana-south_east_district-Gaborone.json

---

content/news/2023-10-09-positconf-chicago-meetup/index.en.md

i think i caught all of the ones that @sheilasaia mentioned, thanks!

fix instances of R-Ladies in posit conf post

---

data/chapters/chile-metropolitana-santiago-de-chile.json
data/chapters/chile-valparaeso-valparaeso.json

+ moving organizer from current to former
+ removing Facebook account

R-Ladies Santiago & Valparaíso Mastodon accounts 

---

data/chapters/united-kingdom-lancaster.json

Add my details as current organiser

Update united-kingdom-lancaster.json organizer details

---

.github/workflows/build.yaml

like the directory workflow, to be able to run checks before merging into blogs-list

try getting specific blogs list version

---

data/global_team/alumni/christin_zasada.json
data/global_team/alumni/claudia_vitolo.json
data/global_team/alumni/erin_ledell.json
data/global_team/alumni/hannah_frick.json
data/global_team/alumni/jennifer_thompson.json
data/global_team/alumni/jesse_mostipak.json
data/global_team/alumni/nadeja_sero.json
data/global_team/alumni/page_piccinini.json
data/global_team/alumni/rachel_kirkham.json

update Jennifer and Nadejda profiles and fix dates.

update alumni info

---

content/about-us/involved/index.en.md

Updating contribution guidelines
- Levels of contribution are included
- Use of emoji for intuitive read

Contribution guidelines updated

---

content/about-us/involved/index.en.md

Updated various links for the get involved page for intuitive read + easy discoverability  
- This is a follow-up for PR #339 
- Based on the suggestion [here](https://github.com/rladies/rladies.github.io/pull/339#issuecomment-2245938029)

Additional links updated for `Get involved page`

---

data/chapters/albania-tirana.json
data/chapters/chile-concepcion.json
data/chapters/ghana-cape-coast.json
data/chapters/mexico-guanajuato.json
data/chapters/mexico-tepic.json
data/chapters/singapore-singapore.json
data/chapters/united-kingdom-sheffield.json
data/chapters/usa-california-irvine.json
data/chapters/usa-pennsylvania-philadelphia.json
data/chapters/usa-wyoming-laramie.json

Update chapter json files

---

data/chapters/usa-colorado-fort-collins.json

When transitioning to the new workflow for onboarding chapters we lost track of this one 💔 
This is the last step to mark their onboarding as completed ✨

update Fort Collins data

---

content/about-us/mission/index.en.md

the prior link wasn't working.

Update data link

---

data/chapters/germany-cologne.json

- Offboard Cosima
- "Onboard" Sara (I think this might have slipped through; Sara is part of R-Ladies Cologne since ~2023 :))

Offboard and onboard R-Ladies Cologne

---

themes/hugo-rladies/layouts/blog/single.html

Fix #379 
Untested, I'm counting on the preview. :sweat_smile:

Remove commit message from posts

---

data/chapters/albania-tirana.json

add new co-organizer + update Meetup link

update Tirana chapter

---

data/global_team/alumni/daniela_vazquez.json
data/global_team/alumni/nicola_rennie.json

Thank you very much for all your hard work and dedication 🤗
https://github.com/rladies/global-team/issues/68
https://github.com/rladies/global-team/issues/65

Offboard multiple former organizers

---

data/chapters/germany-cologne.json

Update Cologne organizers

---

content/form/global-team-application.md

Create redirect for the Global Team Volunteering form

closes #397

---

data/global_team/alumni/alyssa_columbus.json

https://github.com/rladies/global-team/issues/63

Offboard Alyssa

---

config/_default/menu.yaml

MAINT: add CoC to under About section. closes #144  #351

---

content/form/blog-event.md
content/form/blog-submission.md

https://deploy-preview-449--rladies-dev.netlify.app/form/

add forms for blogpost submissions (pretty url)
